### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Xeeeno** [clavinjune/2captcha-example#1]
Hey, it's possible that you make one for [capsolver.com](https://www.capsolver.com/), they have the cheapest and fastest captcha solution of the whole market.
They can solve hcaptcha, recaptcha, amazon waf captcha, turnstile, kasada, akamai, funcaptcha, datadome captcha, geetest etc...
Also you can check their documentation here: https://docs.capsolver.com/

**Comment by clavinjune** [comment]
Hi @Xeeeno, I'm afraid that it's not possible because I'm not open for requests unless it's a sponsorship. I created this repo as a part of a [sponsorship](https://clavinjune.dev/en/blogs/bypass-recaptcha-automatically-using-go/) from 2Captcha. Thank you for your understanding 🙇
